#!/usr/bin/env node
/**
 * groundtruth.test.mjs — self-check for Groundtruth Tier-1 (run: `node groundtruth.test.mjs`).
 * Asserts the non-trivial logic: transcript extraction + the deterministic classifiers,
 * including that an inline-feature diff stays SILENT (the "built inline vs its own unit"
 * Class-7 judgment is the semantic/roadmap call, not a deterministic one). assert-based, no deps.
 */
import assert from 'node:assert';
import { mkdtempSync, writeFileSync as fsWrite, mkdirSync as fsMkdir, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join as pathJoin } from 'node:path';
import { execFileSync } from 'node:child_process';
import { analyze, parseTranscript, scanContent, attributeDebt, runCompiledRules, compileRuleRe, intentConfidence, renderCard, remediationDecision, renderCorrective, openLoops, runProcedures, envFindings, updateTaskLedger, loadGtConfig, pendingApprovals, applyConfirmedDeferrals, humanDeferrals, taskId, refereeTamper, compareSnapshot, integrityScope, GAMED_FILE_RE, priorFindingsContext, sessionHasCommit, proposedStale, isTrackableRequest, isSecret, excludedScanPath, dropExcludedFiles, classifyDeliverables, surfaceOpenLoop } from './groundtruth.mjs';
import { parseCorrectivePairs, parseForbidTokens, isArmableToken, extractCandidates, compile, repoSourceExts } from './compile-rules.mjs';

let pass = 0;
const ok = (label, cond) => { assert.ok(cond, label); console.log(`  ✓ ${label}`); pass++; };
const has = (findings, cls) => findings.some(f => f.cls === cls);

// ── parseTranscript: intent (noise-stripped), bash cmds, results ──
const transcript = [
  JSON.stringify({ type: 'user', isSidechain: false, message: { content: [
    { type: 'text', text: '<ide_opened_file>noise</ide_opened_file>' },
    { type: 'text', text: 'Add a CSV export button to the report page.' },
  ] } }),
  JSON.stringify({ type: 'user', isSidechain: true, message: { content: [
    { type: 'text', text: 'I am a subagent — must be ignored.' },
  ] } }),
  JSON.stringify({ type: 'assistant', message: { content: [
    { type: 'tool_use', name: 'Bash', input: { command: 'npm test' } },
  ] } }),
  JSON.stringify({ type: 'user', message: { content: [
    { type: 'tool_result', is_error: true, content: [{ type: 'text', text: '2 failing' }] },
  ] } }),
].join('\n');
const t = parseTranscript(transcript);
ok('intent = first user text, harness noise stripped', t.intent === 'Add a CSV export button to the report page.');
ok('intent ignores isSidechain subagent entries', !t.intent.includes('subagent'));
ok('bash commands extracted', t.bashCmds.includes('npm test'));
ok('tool_result is_error captured', t.results.some(r => r.is_error === true));

// ── FIXTURE: a slash-command / local-command turn is harness scaffolding, NOT a user ask. Groundtruth
// must abstain on completeness, never grade it 🟢 against caveat boilerplate. (The bug Groundtruth
// surfaced about itself: it captured the <local-command-caveat> envelope as the ASK.) ──
{
  const cmdOnly = JSON.stringify({ type: 'user', isSidechain: false, message: { content: [
    { type: 'text', text: '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these…</local-command-caveat>\n<command-name>groundtruth:groundtruth</command-name>\n<command-args></command-args>' },
  ] } });
  ok('intent: a command-only turn captures NO intent (caveat + scaffolding skipped)',
    parseTranscript(cmdOnly).intent === '');
  const askThenCmd = [
    JSON.stringify({ type: 'user', message: { content: [{ type: 'text', text: '<command-name>groundtruth</command-name>' }] } }),
    JSON.stringify({ type: 'user', message: { content: [{ type: 'text', text: 'Refactor the date parser in utils.js.' }] } }),
  ].join('\n');
  ok('intent: a real ask is still captured when a command turn precedes it',
    parseTranscript(askThenCmd).intent === 'Refactor the date parser in utils.js.');
}
ok('intentConfidence: empty / command-only intent → tier "none" (abstain), not "thin"',
  intentConfidence('').tier === 'none');
ok('renderCard: no gradeable ask → Completeness ⚪ n/a, NOT a 🟢 pass',
  (() => { const c = renderCard([], { intent: '', session: 'x' }); return c.includes('⚪ Completeness — n/a') && !c.includes('🟢 Completeness'); })());
ok('renderCard: a command-only clean turn reads 🟢 Told & Done, not 🟡 LOW-CONFIDENCE',
  (() => { const c = renderCard([], { intent: '', session: 'x' }); return c.includes('🟢 Told & Done') && !c.includes('LOW-CONFIDENCE'); })());

// ── Class 1: false test/build claim ──
ok('C1 fires: claimed tests pass, none ran',
  has(analyze({ claim: 'All tests pass now.', diff: '', bashCmds: [], results: [] }), 1));
ok('C1 warns: claimed pass but a test result reports failures',
  has(analyze({ claim: 'tests pass', bashCmds: ['npm test'], results: [{ is_error: false, text: '3 failed, 5 passed' }] }), 1));
ok('C1 SILENT: "tests should pass" is an example, not a claim (the false-block bug)',
  !has(analyze({ claim: 'name a file and say tests should pass for a full green', bashCmds: [], results: [] }), 1));
ok('C1 SILENT: "make sure tests pass" is guidance, not a claim',
  !has(analyze({ claim: 'make sure tests pass before you merge', bashCmds: [], results: [] }), 1));
ok('C1 SILENT: a stray ✗/Error in the session is not a test failure',
  !has(analyze({ claim: 'tests pass', bashCmds: ['npm test'], results: [{ is_error: true, text: 'Error: command not found ✗' }] }), 1));
ok('C1 silent: claimed pass and a test actually ran clean',
  !has(analyze({ claim: 'tests pass', bashCmds: ['npm test'], results: [{ is_error: false, text: 'ok' }] }), 1));
ok('C1 silent: no test claim at all',
  !has(analyze({ claim: 'Added the button.', bashCmds: [], results: [] }), 1));
ok('C1 fires (anti-game): claimed pass but the only file changed is a test',
  has(analyze({ claim: 'Fixed it, tests pass.', diff: '+++ b/foo.test.js\n+expect(1).toBe(1)', bashCmds: ['npm test'], results: [{ is_error: false, text: 'ok' }] }), 1));
ok('C1 silent: a non-test file also changed (legit test update)',
  !has(analyze({ claim: 'Fixed it, tests pass.', diff: '+++ b/src/foo.js\n+x\n+++ b/foo.test.js\n+y', bashCmds: ['npm test'], results: [{ is_error: false, text: 'ok' }] }), 1));

// ── Class 2: stub/placeholder in added lines ──
ok('C2 fires: TODO in added code',
  has(analyze({ claim: '', diff: '+++ b/a.js\n+  // TODO: wire this up' }), 2));
ok('C2 silent: TODO only in a removed line',
  !has(analyze({ claim: '', diff: '+++ b/a.js\n-  // TODO old' }), 2));

// ── Class 3: silent no-op (past-tense action gating is the precision fix) ──
ok('C3 fires: claimed updating a file absent from the diff',
  has(analyze({ claim: 'Updated cart.js to add the discount.', diff: '+++ b/other.js\n+x' }), 3));
ok('C3 silent: file merely mentioned in prose, no action verb',
  !has(analyze({ claim: 'This is similar to cart.js styling.', diff: '+++ b/other.js\n+x' }), 3));
ok('C3 silent: claimed file IS in the diff',
  !has(analyze({ claim: 'Updated cart.js.', diff: '+++ b/src/cart.js\n+x' }), 3));
// Bug 5 — the extension alternation must not TRUNCATE: a claim about .json/.jsx/.tsx (whose real file IS
// in the diff) must NOT mis-capture .js/.ts and then false-flag it absent. (Pre-fix: 'config.json' ->
// captured 'config.js' -> fired cls:3 naming a file the agent never wrote.)
ok('C3 bug5: a .json claim present in the diff is NOT a false no-op (no js-truncation)',
  !has(analyze({ claim: 'Updated config.json with the new keys.', diff: '+++ b/config.json\n+{"a":1}' }), 3));
ok('C3 bug5: a .jsx claim present in the diff is NOT a false no-op',
  !has(analyze({ claim: 'Added Form.jsx for the modal.', diff: '+++ b/src/Form.jsx\n+x' }), 3));
ok('C3 bug5: a .tsx claim present in the diff is NOT a false no-op',
  !has(analyze({ claim: 'Refactored App.tsx.', diff: '+++ b/src/App.tsx\n+x' }), 3));
// ...but a genuinely-absent .json claim STILL fires (the boundary fix must not blunt real detection).
ok('C3 bug5: a .json claim ABSENT from the diff still fires (detection preserved)',
  has(analyze({ claim: 'Updated config.json.', diff: '+++ b/other.json\n+x' }), 3));
// Line-179 sibling: a bare endsWith(named) let an unrelated suffix-substring path satisfy the claim and
// suppress a real no-op. With basename-only matching, an unrelated `app/xconfig.js` must NOT count.
ok('C3 fires: an unrelated xconfig.js does NOT satisfy a claim about config.js (basename boundary)',
  has(analyze({ claim: 'Updated config.js.', diff: '+++ b/app/xconfig.js\n+x' }), 3));
ok('C3 silent: a legitimately nested src/config.js DOES satisfy the claim (no over-tightening)',
  !has(analyze({ claim: 'Updated config.js.', diff: '+++ b/src/config.js\n+x' }), 3));

// ── General-purpose / multi-language: the engine must work outside JS, not just on one stack ──
{
  // Class 3 — a non-JS filename claim is now recognized (was silently skipped: regex omitted go/rs/rb/…).
  ok('GEN C3: a claimed .go file absent from the diff fires (non-JS no-op now caught)',
    has(analyze({ claim: 'Updated handler.go to add the route.', diff: '+++ b/other.go\n+x' }), 3));
  ok('GEN C3: a claimed .rs file absent fires',
    has(analyze({ claim: 'Wrote lib.rs.', diff: '+++ b/main.rs\n+x' }), 3));
  ok('GEN C3: a .rb claim present in the diff is silent (no false no-op)',
    !has(analyze({ claim: 'Fixed user.rb.', diff: '+++ b/app/models/user.rb\n+x' }), 3));

  // Class 2 — idiomatic non-JS/Python stubs are caught (Rust/Go/Java/Kotlin), not just TODO comments.
  ok('GEN C2: Rust todo!() / unimplemented!() are stubs',
    has(analyze({ claim: '', diff: '+++ b/lib.rs\n+fn f() { todo!() }' }), 2) &&
    has(analyze({ claim: '', diff: '+++ b/lib.rs\n+fn g() { unimplemented!() }' }), 2));
  ok('GEN C2: Go panic("not implemented") is a stub',
    has(analyze({ claim: '', diff: '+++ b/h.go\n+func F() { panic("not implemented") }' }), 2));
  ok('GEN C2: Java NotImplementedException + Kotlin TODO() are stubs',
    has(analyze({ claim: '', diff: '+++ b/A.java\n+throw new NotImplementedException();' }), 2) &&
    has(analyze({ claim: '', diff: '+++ b/A.kt\n+fun f() = TODO()' }), 2));
  ok('GEN C2 silent: a `todos` identifier is NOT a stub (TODO needs a word boundary)',
    !has(analyze({ claim: '', diff: '+++ b/a.js\n+const todos = []' }), 2));

  // Class 1 — a non-JS test RUNNER counts as "tests ran" (no false BLOCK on Go/Rust/Ruby/Java/.NET/Python).
  for (const cmd of ['go test ./...', 'cargo test', 'bundle exec rspec', './gradlew test', 'pytest -q', 'dotnet test', 'mvn verify']) {
    ok(`GEN C1: '${cmd}' is recognized as a test run (claimed-pass does not false-block)`,
      !has(analyze({ claim: 'tests pass', bashCmds: [cmd], results: [{ is_error: false, text: 'ok' }] }), 1));
  }
  ok('GEN C1: a go-test FAILURE result still warns under a pass claim (two-sided detection)',
    has(analyze({ claim: 'tests pass', bashCmds: ['go test ./...'], results: [{ is_error: false, text: '--- FAIL: TestThing (0.00s)' }] }), 1));

  // Class 4 — phantom-ref is language-aware: Ruby require_relative resolves; package-qualified / dotted /
  // markup languages ABSTAIN (emit nothing) rather than false-flag against JS resolution.
  ok('GEN C4: a Ruby require_relative to an absent file fires (resolved relative to the .rb file)',
    has(analyze({ claim: '', cwd: '/tmp', diff: '+++ b/lib.rb\n+require_relative "./__gt_absent_xyz__"' }), 4));
  ok('GEN C4 abstain: a Go import line does NOT phantom-flag (package-qualified, not path-relative)',
    !has(analyze({ claim: '', cwd: '/tmp', diff: '+++ b/main.go\n+import "./helper"' }), 4));
  ok('GEN C4 abstain: a Python `from .x import` does NOT phantom-flag (dotted/package import)',
    !has(analyze({ claim: '', cwd: '/tmp', diff: '+++ b/app.py\n+from .helper import thing' }), 4));
  ok('GEN C4 abstain: an import-shaped line in a .md doc does NOT phantom-flag (latent FP closed)',
    !has(analyze({ claim: '', cwd: '/tmp', diff: '+++ b/README.md\n+import "./example"' }), 4));

  // Test-file detection across languages (anti-gaming guard).
  ok('GEN test-file: Go _test.go, Python test_*.py, Ruby _spec.rb are recognized as test files',
    GAMED_FILE_RE.test('pkg/foo_test.go') && GAMED_FILE_RE.test('tests/test_foo.py') && GAMED_FILE_RE.test('spec/user_spec.rb'));
  ok('GEN C1 anti-game: claimed pass but the only changed file is a Go test fires',
    has(analyze({ claim: 'Fixed it, tests pass.', diff: '+++ b/pkg/foo_test.go\n+x', bashCmds: ['go test ./...'], results: [{ is_error: false, text: 'ok' }] }), 1));

  // compile-rules — a doc-extracted rule is scoped to the repo's ACTUAL languages, not hardcoded JS/SQL.
  ok('GEN rules: repoSourceExts derives scope from the repo files (Python/Ruby repo → py,rb; docs excluded)',
    (() => { const e = repoSourceExts('/x', () => 'app.py\nlib/util.py\nmodels/user.rb\nREADME.md\n'); return e.includes('py') && e.includes('rb') && !e.includes('md'); })());
  ok('GEN rules: an empty/unknown repo falls back to the broad default scope (rule still has SOME scope)',
    repoSourceExts('/x', () => '').length > 10);
}

// ── Inline-feature case: the deterministic checks must stay SILENT (the "built inline vs its own unit" Class-7 call is the semantic/roadmap layer, not deterministic) ──
const inlineFeatureDiff = [
  '+++ b/src/upload.js',
  '+let _retryState = null;',
  '+async function uploadWithBackoff(file) {',
  '+  for (let attempt = 0; attempt < 3; attempt++) _retryState = attempt;',
  '+}',
  '+++ b/src/client.js',
  '+export const upload = (f) => uploadWithBackoff(f);',
].join('\n');
const scFindings = analyze({ claim: 'Added retry/backoff to the upload client.', diff: inlineFeatureDiff });
ok('inline-feature diff trips NO deterministic class (correctly silent — it is a semantic/roadmap call)', scFindings.length === 0);

// ── Audit mode: scanContent (whole-file debt scan, no diff/claim) ──
const auditHits = scanContent('lib/foo.js', 'const x = 1;\n// TODO: handle errors\nimport { y } from "./missing-mod";\n');
ok('audit C2 fires on a TODO with line number', auditHits.some(f => f.cls === 2 && f.line === 2));
ok('audit C4 fires on an unresolved relative import', auditHits.some(f => f.cls === 4 && f.line === 3));
ok('audit silent on clean lines', !scanContent('a.js', 'const ok = 1;\nreturn ok;\n').length);
// Precision regressions — these were real false positives caught in the field:
ok('audit silent on prose "not implemented" (design note, not a stub)',
  !scanContent('a.js', ' *  appears near a similar number (not implemented precisely; simpler for now)\n').some(f => f.cls === 2));
ok('audit silent on a quoted external "...is not implemented" error',
  !scanContent('m.js', '// errors with "EXECUTE of transaction commands is not implemented"\n').some(f => f.cls === 2));
ok('audit FIRES on a real thrown not-implemented stub',
  scanContent('a.js', 'function x(){ throw new Error("not implemented"); }\n').some(f => f.cls === 2));
ok('audit silent on a bare "..." line in JS (spread/elision, not a stub)',
  !scanContent('a.js', '  ...\n').some(f => f.cls === 2));

// ── §5 baseline attribution: introduced vs pre-existing ──
{
  const cur = scanContent('lib/x.js', '// TODO: a\n// TODO: b\n');         // two debt items
  const baselineKeys = [`lib/x.js::// TODO: a`];                            // 'a' existed at session start
  const { introduced, preExisting } = attributeDebt(baselineKeys, cur);
  ok('baseline: pre-existing debt is not attributed to the session', preExisting.some(f => /TODO: a/.test(f.msg)));
  ok('baseline: newly-introduced debt is attributed to the session', introduced.some(f => /TODO: b/.test(f.msg)));
  ok('baseline: with no baseline keys, everything counts as introduced', attributeDebt(null, cur).introduced.length === 2);
}

// ── Security (B1 RLS / C1 key / C2 private key). Secret literals are concatenated so the test
//    source itself never matches the scanner (the same self-match safety the patterns are built for).
ok('B1 fires: new table created without RLS in the same change',
  has(analyze({ diff: '+++ b/migrations/099_x.sql\n+CREATE TABLE public.scores (id int);' }), 'B1'));
ok('B1 silent: new table WITH ENABLE ROW LEVEL SECURITY in the same change',
  !has(analyze({ diff: '+++ b/migrations/099_x.sql\n+CREATE TABLE public.scores (id int);\n+ALTER TABLE public.scores ENABLE ROW LEVEL SECURITY;' }), 'B1'));
ok('B1 silent: CREATE TABLE only MENTIONED in a non-sql doc/skill (no false-fire)',
  !has(analyze({ diff: '+++ b/.claude/skills/security/SKILL.md\n+Every `CREATE TABLE public.foo` must enable RLS.' }), 'B1'));
ok('B3 fires: permissive USING(true) policy added in sql (the anon-readable hole)',
  has(analyze({ diff: '+++ b/migrations/070_p.sql\n+CREATE POLICY r ON public.teachers FOR SELECT TO public USING (true);' }), 'B3'));
ok('B3 silent: USING(true) only mentioned in a doc',
  !has(analyze({ diff: '+++ b/docs/security.md\n+Never write a policy with USING (true) on a PII table.' }), 'B3'));
ok('B3 silent: USING(true) only in a -- comment inside a .sql migration (the 068 false positive)',
  !has(analyze({ diff: '+++ b/migrations/068_rls.sql\n+-- drop the bad policies (all were permissive TO public USING (true))\n+DROP POLICY IF EXISTS r ON public.teachers;' }), 'B3'));
ok('B1 silent: CREATE TABLE only quoted in a -- comment inside a .sql file',
  !has(analyze({ diff: '+++ b/migrations/068_rls.sql\n+-- the old CREATE TABLE public.scores had no RLS' }), 'B1'));
ok('B3 fires: a REAL USING(true) policy still trips even with a trailing -- comment',
  has(analyze({ diff: '+++ b/migrations/070_p.sql\n+CREATE POLICY r ON public.t FOR SELECT TO public USING (true); -- wide open' }), 'B3'));
const awsKey = 'AKIA' + 'ABCDEFGHIJKLMNOP';                 // AKIA + 16 → matches at runtime, not in source
ok('C1 fires: AWS key hardcoded in added code',
  has(analyze({ diff: '+++ b/config.js\n+const k = "' + awsKey + '";' }), 'C1'));
ok('C1 silent: same key only on a REMOVED line (not added)',
  !has(analyze({ diff: '+++ b/config.js\n-const k = "' + awsKey + '";' }), 'C1'));
const pem = '-----BEGIN ' + 'RSA' + ' PRIVATE KEY-----';
ok('C2 fires: private key header in added code',
  has(analyze({ diff: '+++ b/id_rsa\n+' + pem }), 'C2'));
ok('security silent on a clean code diff',
  analyze({ diff: '+++ b/src/a.js\n+export const ok = 1;' }).every(f => !['B1', 'C1', 'C2'].includes(f.cls)));

// ── §10 compiled rules: prose → deterministic predicate evaluator ──
const cr = runCompiledRules;
ok('compiled forbid_path: flags a forbidden file path, WARN by default (auto-compiled never blocks)',
  cr('+++ b/public/admin.html\n+<x>', [{ id: 'no-admin', kind: 'forbid_path', file_re: 'public/admin\\.html$', message: 'admin.html is local-only' }]).some(f => f.cls === 'R' && f.sev === 'warn'));
ok('compiled forbid_in_added: flags a forbidden pattern in a matching file',
  cr('+++ b/src/a.js\n+  console.log(x)', [{ id: 'no-log', kind: 'forbid_in_added', file_re: '\\.js$', line_re: 'console\\.log', message: 'no console.log' }]).some(f => f.cls === 'R'));
ok('compiled forbid_in_added (B2): a same-turn inline exemption is SURFACED as a warn (suppression is visible, not silent)',
  (() => { const r = cr('+++ b/src/a.js\n+// groundtruth-ok\n+console.log(x)', [{ id: 'no-log', kind: 'forbid_in_added', file_re: '\\.js$', line_re: 'console\\.log', unless_re: 'groundtruth-ok', message: 'x' }]); return r.length === 1 && r[0].sev === 'warn' && /suppress/i.test(r[0].msg); })());
ok('compiled: human-promoted severity:block is honored',
  cr('+++ b/x.js\n+danger', [{ id: 'd', kind: 'forbid_in_added', file_re: '\\.js$', line_re: 'danger', severity: 'block', message: 'x' }]).some(f => f.sev === 'block'));
ok('compiled: a malformed regex is SURFACED as INERT (not silently skipped — armed-but-dead is false confidence)',
  (() => { const r = cr('+++ b/x.js\n+y', [{ id: 'bad', kind: 'forbid_in_added', file_re: '\\.js$', line_re: '(', message: 'x' }]); return r.length === 1 && r[0].sev === 'warn' && /INERT/i.test(r[0].msg); })());
ok('compiled: a `(?i)` PCRE inline flag is normalized so the rule FIRES (JS RegExp rejects inline groups — this used to die silently)',
  cr('+++ b/migrations/repeatable/x.sql\n+CREATE TABLE t (id int)', [{ id: 'no-ct', kind: 'forbid_in_added', file_re: 'repeatable/.*\\.sql$', line_re: '(?i)\\bCREATE\\s+TABLE\\b', message: 'x' }]).some(f => f.rule === 'no-ct' && !/INERT/i.test(f.msg)));
ok('compileRuleRe: strips a leading (?i) (stays case-insensitive) but still throws on a genuinely broken pattern',
  (() => { const fires = compileRuleRe('(?i)\\bfoo\\b').test('FOO'); let threw = false; try { compileRuleRe('('); } catch { threw = true; } return fires && threw; })());
ok('compiled: no rules → no findings', cr('+++ b/x.js\n+y', []).length === 0);
// Surfacing: the prior turn's findings get injected into the next turn's context (closes the silent-warn gap).
ok('priorFindingsContext: clean / non-warn input → no injection',
  priorFindingsContext([]) === '' && priorFindingsContext([{ cls: 1, sev: 'note', msg: 'x' }]) === '');
ok('priorFindingsContext: warn/block findings → an FYI block (do-not-reply) listing them by class + msg',
  (() => { const c = priorFindingsContext([{ cls: 9, sev: 'warn', msg: 'branches on CI' }, { cls: 'C1', sev: 'block', msg: 'secret' }]);
    return /awareness only/i.test(c) && /do not reply/i.test(c) && /special-casing/i.test(c) && /branches on CI/.test(c) && /secret/.test(c); })());
// Missing-baseline FP: a baseline absent because SessionStart never ran (plugin reinstalled mid-session)
// with NO commit this session is benign — must NOT block. Only committed-this-session work is a real blind spot.
ok('sessionHasCommit: a git commit / merge / gh pr merge in the recorded commands → true',
  sessionHasCommit(['ls', 'git commit -m x']) && sessionHasCommit(['git merge main']) && sessionHasCommit(['gh pr merge 5']));
ok('sessionHasCommit: read-only / no-commit commands → false (a missing baseline with no commit is benign, not a block)',
  !sessionHasCommit(['git status', 'git diff HEAD', 'node t.mjs', 'ls -la']) && !sessionHasCommit([]));
// B1 — a rule whose unless_re matches everything is INERT (armed but can never fire): surfaced, not silent.
ok('compiled (B1): an unless_re of `.*` makes the rule INERT, surfaced as a warn (not silently passing)',
  (() => { const r = cr('+++ b/a.js\n+danger', [{ id: 'no-danger', kind: 'forbid_in_added', file_re: '\\.js$', line_re: 'danger', unless_re: '.*', message: 'x' }]); return r.length === 1 && r[0].sev === 'warn' && /INERT/i.test(r[0].msg); })());
ok('compiled (B1): a normal unless_re (groundtruth-ok) is NOT flagged inert (only total-suppression is)',
  !cr('+++ b/a.js\n+danger', [{ id: 'no-danger', kind: 'forbid_in_added', file_re: '\\.js$', line_re: 'danger', unless_re: 'groundtruth-ok', message: 'x' }]).some(f => /INERT/i.test(f.msg)));

// ── Class 9: special-casing / overfit — non-test source that detects it's under test/CI/audit (warn-only) ──
{
  const c9 = (diff) => has(analyze({ claim: '', diff }), 9);
  ok('C9 (gaming GT): non-test source reading the plugin\'s own env var fires',
    c9('+++ b/src/app.js\n+if (process.env.GROUNDTRUTH_BLOCK) return fakeResult();'));
  ok('C9 (gaming GT): a groundtruth-disable token written into source fires',
    c9('+++ b/src/app.js\n+const x = compute(); // groundtruth-disable'));
  ok('C9 (CI branch): non-test source branching on process.env.CI fires',
    c9('+++ b/src/app.js\n+if (process.env.CI) { return cached; }'));
  ok('C9 (env probe): a Python os.environ CI check in source fires',
    c9('+++ b/src/svc.py\n+if os.environ.get("CI"): return STUB'));
  ok('C9 abstain: the SAME branch inside a TEST file does NOT fire (legit test-mode config)',
    !c9('+++ b/src/app.test.js\n+if (process.env.CI) { return cached; }'));
  ok('C9 abstain: a non-source file (.md) does NOT fire',
    !c9('+++ b/README.md\n+set process.env.CI in the runner'));
  ok('C9 silent: ordinary source with no evaluator branch does NOT fire',
    !c9('+++ b/src/app.js\n+const total = items.reduce((a, b) => a + b, 0);'));
  ok('C9: at most one finding per turn (a smell to confirm, not a spammer)',
    analyze({ claim: '', diff: '+++ b/src/a.js\n+if (process.env.CI) a();\n+if (process.env.CI) b();' }).filter(f => f.cls === 9).length === 1);
}

// ── §7 pre-flight intent: can the contract's completeness be checked? ──
ok('intent thin: vague one-liner', intentConfidence('fix it').tier === 'thin');
ok('intent none: empty prompt is not gradeable (abstain, not "thin")', intentConfidence('').tier === 'none');
ok('intent tight: names a file', intentConfidence('add a CSV export to report.js').tier === 'tight');
ok('intent tight: names a camelCase symbol', intentConfidence('refactor handleSubmit to debounce').tier === 'tight');
ok('intent tight: has a concrete deliverable noun', intentConfidence('add a share button to the end screen').tier === 'tight');
ok('intent tight: states a test expectation', intentConfidence('handle empty input, tests should pass').tier === 'tight');
ok('card marks a thin-contract clean verdict LOW-CONFIDENCE', renderCard([], { intent: 'fix it' }).includes('LOW-CONFIDENCE'));
ok('card does NOT low-confidence a tight contract', !renderCard([], { intent: 'add a button to report.js' }).includes('LOW-CONFIDENCE'));

// ── Phase-1 false-completion acceptance harness (spec §5; zero false positives on the negatives) ──
ok('FIXTURE 1 — claimed Done while the workflow is still running → FAIL (async_done)',
  has(analyze({ claim: "🟢 Told & Done — clean. Waiting on the verification workflow (wf_1bb); I'll deliver the report when it completes." }), 'async_done'));
ok('FIXTURE 2 — "all tests pass" with no test command run → FAIL (test_build)',
  has(analyze({ claim: 'all tests pass', bashCmds: [], results: [] }), 1));
ok('FIXTURE 3 — "all tests pass" with npm test exit 0 → PASS (no false positive)',
  !has(analyze({ claim: 'all tests pass', bashCmds: ['npm test'], results: [{ is_error: false, text: 'ok 12 passing' }] }), 1));
ok('FIXTURE 4 — "Done!" on a pure explanation, no test/async claim → ABSTAIN (no finding)',
  analyze({ claim: 'Done! Here is how the function works.', bashCmds: [], results: [] }).length === 0);
ok('async_done abstains when "done" has NO deferral signal (precision guard)',
  !has(analyze({ claim: 'Done — added the button and it works.' }), 'async_done'));
// disk/transcript-grounded recall path: a launched background task with no completion record
ok('async_done (grounded): "all done" + a background task pending → FAIL (even with no "in progress" phrasing)',
  has(analyze({ claim: 'All done — shipped the report.', bgPending: true }), 'async_done'));
ok('async_done abstains: "all done", nothing pending → ABSTAIN (precision)',
  !has(analyze({ claim: 'All done — shipped the report.', bgPending: false }), 'async_done'));
{
  const launch = [
    JSON.stringify({ type: 'user', message: { content: [{ type: 'text', text: 'run the audit' }] } }),
    JSON.stringify({ type: 'assistant', message: { content: [{ type: 'tool_use', name: 'Workflow', input: {} }] } }),
  ].join('\n');
  ok('parseTranscript: launched workflow with no completion → bgPending=true', parseTranscript(launch).bgPending === true);
  const done = launch + '\n' + JSON.stringify({ type: 'user', message: { content: [{ type: 'text', text: '<task-notification><status>completed</status></task-notification>' }] } });
  ok('parseTranscript: workflow + completion notice → bgPending=false', parseTranscript(done).bgPending === false);
}

ok('verdict reads "IN PROGRESS — not done" when async_done fires (not "Told & Done", not generic WARN)',
  (() => { const c = renderCard(analyze({ claim: "🟢 Told & Done — clean. Waiting on the workflow; I'll deliver when it completes." }), {});
    return c.includes('IN PROGRESS') && !c.includes('Told & Done'); })());

// ── Remediation loop: retry cap → escalate, anti-gaming (§13/§14) ──
ok('remediation: first catch → block, attempt → 1', remediationDecision({ attempts: 0 }).action === 'block' && remediationDecision({ attempts: 0 }).nextAttempts === 1);
ok('remediation: attempt 1 → block again (within cap)', remediationDecision({ attempts: 1 }).action === 'block');
ok('remediation: at the cap (2) → escalate, not block', remediationDecision({ attempts: 2 }).action === 'escalate');
ok('remediation: a gamed fix attempt KEEPS the block (gaming is not an escape hatch) + flags a human', (() => { const d = remediationDecision({ attempts: 1, gamed: true }); return d.action === 'block' && d.gamed === true; })());
ok('corrective payload names the target state for the class',
  renderCorrective([{ cls: 1, sev: 'block', msg: 'x' }], 1).includes('Run the test/build you claimed'));
ok('corrective payload warns against gaming the checker',
  /do not edit the tests/i.test(renderCorrective([{ cls: 'B3', sev: 'block', msg: 'x' }], 2)));

// ── No-git: reconstruct the diff from the tool-call ledger (Edit/Write/MultiEdit) ──
{
  const t = JSON.stringify({ type: 'assistant', message: { content: [{ type: 'tool_use', name: 'Write', input: { file_path: 'src/a.js', content: 'function x(){\n  // TODO wire this up\n}' } }] } });
  const p = parseTranscript(t);
  ok('no-git: parseTranscript synthesizes a +diff from a Write tool call', /\+\+\+ b\/src\/a\.js/.test(p.toolDiff));
  ok('no-git: the synthesized diff feeds the checks (stub caught without git)', has(analyze({ diff: p.toolDiff }), 2));
}
{
  const t = JSON.stringify({ type: 'assistant', message: { content: [{ type: 'tool_use', name: 'Edit', input: { file_path: 'migrations/x.sql', old_string: '', new_string: 'CREATE TABLE public.t (id int);' } }] } });
  ok('no-git: an Edit to a .sql is reconstructed → RLS-off table caught (B1)', has(analyze({ diff: parseTranscript(t).toolDiff }), 'B1'));
}
ok('no-git: no Edit/Write calls → empty toolDiff (nothing to check)',
  parseTranscript(JSON.stringify({ type: 'user', message: { content: [{ type: 'text', text: 'hi' }] } })).toolDiff === '');

// ── FP fix: a NEW file created this session lives only in the tool ledger (`git diff` ignores
// untracked files). main() now merges the ledger into the diff, which must clear the false
// silent-no-op that flagged a freshly-created file as "claimed but absent from the diff". ──
{
  const gitDiff = '+++ b/src/existing.js\n+const x = 1;';   // an unrelated tracked change
  const ledger = parseTranscript(JSON.stringify({ type: 'assistant', message: { content: [
    { type: 'tool_use', name: 'Write', input: { file_path: 'public/js/host-base.js', content: 'export const surfaceUrl = () => {};' } }] } })).toolDiff;
  ok('FP: a new untracked file IS flagged from git diff alone (reproduces the bug)',
    has(analyze({ claim: 'Created host-base.js.', diff: gitDiff }), 3));
  ok('FP: merging the tool ledger (the main() fix) clears the false silent-no-op',
    !has(analyze({ claim: 'Created host-base.js.', diff: gitDiff + '\n' + ledger }), 3));
}

// ── Contract memory: parseTranscript captures the WHOLE conversation's asks (not just #1), and
// openLoops nudges asks whose named deliverable never landed — abstaining when none is named. ──
{
  const t = [
    JSON.stringify({ type: 'user', message: { content: [{ type: 'text', text: 'Build the procedural engine in groundtruth.mjs.' }] } }),
    JSON.stringify({ type: 'assistant', message: { content: [{ type: 'text', text: 'on it' }] } }),
    JSON.stringify({ type: 'user', message: { content: [{ type: 'text', text: 'Also add the rule-compiler in compiler.mjs.' }] } }),
    JSON.stringify({ type: 'user', message: { content: [{ type: 'text', text: 'make all the changes' }] } }),
  ].join('\n');
  const p = parseTranscript(t);
  ok('memory: parseTranscript captures ALL asks across messages, not just the first',
    p.asks.length === 3 && p.intent === 'Build the procedural engine in groundtruth.mjs.');
  // a diff that delivers groundtruth.mjs but NOT compiler.mjs → that ask is an open loop
  const diff = '+++ b/hooks/groundtruth.mjs\n+export function procedural(){}';
  const open = openLoops(p.asks, diff);
  ok('open loop: an ask naming a deliverable absent from the diff is flagged',
    open.some(o => /compiler\.mjs/i.test(o.ask)));
  ok('open loop: an ask whose deliverable IS in the diff is NOT flagged',
    !open.some(o => /groundtruth\.mjs/i.test(o.ask)));
  ok('open loop: a vague ask naming no deliverable is NOT nagged (abstain)',
    openLoops(['make all the changes'], '').length === 0);
}

// ── Procedural compliance: required / forbidden / ordered commands over the transcript's tool calls ──
{
  const PROCS = [
    { id: 'no-prod', kind: 'forbid_present', match: 'migrate:prod\\b(?!:dry)', message: 'real prod write' },
    { id: 'dry-first', kind: 'require_order', before: ':dry\\b|--dry-run', after: 'npm run migrate:staging\\b(?!:dry)', message: 'dry-run first' },
    { id: 'needs-test', kind: 'require_present', when: 'git commit', match: 'node .*\\.test\\.', message: 'committed without running a test' },
  ];
  ok('procedure forbid_present: a real prod migrate is flagged',
    runProcedures(['npm run migrate:prod'], PROCS).some(f => /real prod write/.test(f.msg)));
  ok('procedure forbid_present: a prod :dry run is NOT flagged',
    !runProcedures(['npm run migrate:prod:dry'], PROCS).some(f => /real prod write/.test(f.msg)));
  ok('procedure require_order: real migrate with NO prior dry-run is flagged',
    runProcedures(['npm run migrate:staging'], PROCS).some(f => /dry-run first/.test(f.msg)));
  ok('procedure require_order: real migrate WITH a prior :dry is clean',
    !runProcedures(['npm run migrate:staging:dry', 'npm run migrate:staging'], PROCS).some(f => /dry-run first/.test(f.msg)));
  ok('procedure require_present: git commit with no test run is flagged',
    runProcedures(['git commit -m x'], PROCS).some(f => /without running a test/.test(f.msg)));
  ok('procedure require_present: git commit WITH a test run is clean',
    !runProcedures(['node hooks/x.test.mjs', 'git commit -m x'], PROCS).some(f => /without running a test/.test(f.msg)));
}

// ── env-file exposure (security) — committed .env = block, present-but-unignored = warn, example = exempt ──
{
  ok('env: a TRACKED .env is a block (secret in history)',
    envFindings(['app/.env'], []).some(f => f.cls === 'ENV' && f.sev === 'block'));
  ok('env: an untracked, un-ignored .env.local is a warn',
    envFindings([], ['.env.local']).some(f => f.cls === 'ENV' && f.sev === 'warn'));
  ok('env: .env.production is flagged (real env, not exempt)',
    envFindings(['.env.production'], []).some(f => f.cls === 'ENV'));
  ok('env: .env.example is EXEMPT (meant to be committed)',
    envFindings(['.env.example'], []).length === 0);
  ok('env: .env.sample / .env.template are exempt',
    envFindings(['config/.env.sample', '.env.template'], []).length === 0);
  ok('env: a properly-ignored .env (in NEITHER list) is silent',
    envFindings([], []).length === 0);
  ok('env: a normal source file is never an env finding',
    envFindings(['api/_lib/env.js', 'src/environment.ts'], ['lib/dotenv.js']).length === 0);
}

// ── md-extractor: parse `correct` (not `wrong`) corrective pairs, and only arm real-identifier tokens ──
{
  ok('extractor: parses a single corrective pair',
    parseCorrectivePairs('`users.created_at` (not `signup_date`)').some(p => p.correct === 'users.created_at' && p.wrong === 'signup_date'));
  ok('extractor: parses MULTIPLE pairs on one line (the SCHEMA gotcha line form)',
    parseCorrectivePairs('use `orders.is_paid` (not `paid_flag`) and `events.starts_at` (not `start_year`)').length === 2);
  ok('extractor: a line with no corrective pair yields nothing',
    parseCorrectivePairs('`example.com/` → `index.html` (the home page)').length === 0);
  ok('extractor: real identifiers are armable',
    isArmableToken('signup_date') && isArmableToken('DATABASE_URL') && isArmableToken('paid_flag'));
  ok('extractor: a leading-underscore partial like `_API_KEY` is NOT armed (would mis-anchor)',
    !isArmableToken('_API_KEY'));
  ok('extractor: too-short / non-identifier tokens are not armed',
    !isArmableToken('a') && !isArmableToken('to') && !isArmableToken('1x'));
  // extractCandidates with an injected grep (no git) — proves the doc→candidate pipe end-to-end, hermetic.
  const fakeGrep = () => 'CLAUDE.md:74:`users.created_at` (not `signup_date`) and `x` (not `_API_KEY`)\n';
  const cands = extractCandidates('/x', fakeGrep);
  ok('extractor: builds a forbid_in_added candidate from a doc line, with provenance',
    cands.length === 1 && cands[0].kind === 'forbid_in_added' && /signup_date/.test(cands[0].line_re) && /CLAUDE\.md:74/.test(cands[0].source));
  ok('extractor: the non-armable token on that same line is dropped',
    !cands.some(c => /_API_KEY/.test(c.line_re)));

  // The narrow-extraction fix: the no-paren form is how SCHEMA.md states gotchas; it was silently missed.
  ok('extractor: parses the NO-PAREN corrective form (`X` not `Y`) — the SCHEMA.md gotcha shape',
    parseCorrectivePairs('`users.created_at` not `signup_date`').some(p => p.correct === 'users.created_at' && p.wrong === 'signup_date'));
  ok('extractor: no-paren form tolerates bold/punctuation between (`X`** not `Y`, `X`, not `Y`)',
    parseCorrectivePairs('use **`events.starts_at`** not `start_year`').some(p => p.wrong === 'start_year'));
  ok('extractor: the [^`] guard pairs the NEAR token, never leaps a backtick (`a` and `b` are not `c` → b,c)',
    (() => { const p = parseCorrectivePairs('`a` and `b` are not `c`'); return p.length === 1 && p[0].correct === 'b' && p[0].wrong === 'c'; })());

  // Explicit forbid form: never `X` / do not use `X`.
  ok('forbid: parses "never `X`" and "do not use `X`"',
    parseForbidTokens('never `import.meta` here').some(f => f.wrong === 'import.meta') &&
    parseForbidTokens('do not use `eval` ever').some(f => f.wrong === 'eval'));
  ok('forbid: requires the backtick token adjacent — "never going to `x`" does NOT match',
    parseForbidTokens('never going to `x` change').length === 0);

  // compile() = extract + GROUND. One injected doc line carries a corrective (paid_flag) AND a forbid
  // (map noun); injected code-grep makes `map` match code and `paid_flag` not. This proves both halves:
  // broadening pulls the forbid, and grounding routes the over-broad one to review — never auto-arms it.
  const docGrep = () => 'docs/x.md:5:`orders.is_paid` not `paid_flag`, and never `map` as a round image\n';
  const code = (_root, line_re) => /map/.test(line_re) ? ['f.js:1: items.map(y)'] : [];   // map is everywhere; paid_flag is not
  const proposed = compile('/x', { code, grep: docGrep });
  const pub = proposed.find(c => /paid_flag/.test(c.line_re));
  const mapRule = proposed.find(c => /\\bmap\\b/.test(c.line_re));
  ok('compile: a doc line yields BOTH the corrective (paid_flag) and the forbid (map) candidate',
    !!pub && !!mapRule);
  ok('compile/ground: zero-code-hit candidate is "armable", a code-matching one is "review" (not auto-armed)',
    pub.status === 'armable' && mapRule.status === 'review' && mapRule.hits === 1);
  // Genericness: the plugin ships NO project-specific rules. A repo with no seed-rules.json gets back
  // ONLY what its own docs yield — nothing hardcoded (no project-specific rules baked into the plugin).
  ok('compile: ships zero hardcoded project rules — proposed = only this repo\'s own doc-extracted rules',
    proposed.length === 2 && proposed.every(c => /paid_flag|\\bmap\\b/.test(c.line_re)));
}

// ── Permission gate: nothing armed until a human approves; the card nudge counts unapproved cleans ──
{
  ok('pendingApprovals: missing files → 0 (no crash, nothing to nudge)',
    pendingApprovals('/nonexistent/path/xyz') === 0);
  ok('renderCard surfaces the approval nudge when clean rules await approval',
    /await approval/.test(renderCard([], { session: 's', intent: 'do a thing in x.js', pendingRules: 3 })));
  ok('renderCard omits the nudge when nothing is pending',
    !/await approval/.test(renderCard([], { session: 's', intent: 'do a thing in x.js', pendingRules: 0 })));
}

// ── §11 referee-state tamper tripwire — the agent reaching BACK to rewrite the checker's OWN ground
//    truth (rules / block switch / ledger). Severity anchored to ENV (not config); a write is legit only
//    if ratified by the unforgeable slash-command turn. ──
{
  const W = (p) => `+++ b/${p}\n+[]`;   // a write to path p in the (tool-)diff
  ok('tamper: an agent write to compiled-rules.json (no ratifying command) fires the meta-check',
    refereeTamper(W('.claude/groundtruth/compiled-rules.json'), new Set(), false).some(f => f.cls === 'tamper'));
  ok('tamper: severity anchors to ENV authority — block when env=1, warn otherwise (config gets no vote)',
    refereeTamper(W('.claude/groundtruth/compiled-rules.json'), new Set(), true)[0].sev === 'block' &&
    refereeTamper(W('.claude/groundtruth/compiled-rules.json'), new Set(), false)[0].sev === 'warn');
  ok('tamper: a rules write RATIFIED by the human running /groundtruth-rules is legitimate (not flagged)',
    refereeTamper(W('.claude/groundtruth/compiled-rules.json'), new Set(['groundtruth-rules']), false).length === 0);
  ok('tamper: config.json is ratified only by /groundtruth-block — the wrong command does not excuse it',
    refereeTamper(W('.claude/groundtruth/config.json'), new Set(['groundtruth-rules']), false).some(f => f.cls === 'tamper') &&
    refereeTamper(W('.claude/groundtruth/config.json'), new Set(['groundtruth-block']), false).length === 0);
  ok('tamper: a normal source write is NOT referee-state tampering', refereeTamper(W('src/app.js'), new Set(), true).length === 0);
  // THE fixture the design demands: writing compiled-rules.json:[] cannot silence its own alarm.
  ok('tamper FIXTURE: writing compiled-rules.json:[] still fires at full env-anchored severity — alarm un-cuttable',
    refereeTamper('+++ b/.claude/groundtruth/compiled-rules.json\n+[]', new Set(), true)[0].sev === 'block');
  // NB: the Bash/MCP write channel (config-flip, snapshot forge/delete, rules disarm) is no longer scanned
  // here from the command stream (that substring sensor re-fired on STALE cumulative-transcript commands and
  // matched read-only `cat/ls`). Its WRITE EFFECT is caught precisely by compareSnapshot (out-of-band hash
  // change) + the snapshot-absent check — see the D9 block below.
  ok('parseTranscript: captures slash-command invocations as the unforgeable ratification signal',
    parseTranscript(JSON.stringify({ type: 'user', message: { content: [{ type: 'text', text: '<command-name>groundtruth-rules</command-name>' }] } })).commandsInvoked.has('groundtruth-rules'));
  // Regression: a NAMESPACED + slashed plugin command (/groundtruth:groundtruth-rules) must ratify the
  // bare 'groundtruth-rules' — else arming rules via the sanctioned command false-fires tamper on its
  // own compiled-rules.json write (observed live).
  const nsTx = parseTranscript(JSON.stringify({ type: 'user', message: { content: [{ type: 'text', text: '<command-name>/groundtruth:groundtruth-rules</command-name>' }] } }));
  ok('parseTranscript: a namespaced/slashed plugin command normalizes to its bare suffix', nsTx.commandsInvoked.has('groundtruth-rules'));
  ok('tamper: arming via /groundtruth:groundtruth-rules ratifies its OWN compiled-rules.json write (no false positive)',
    refereeTamper('+++ b/.claude/groundtruth/compiled-rules.json\n+[]', nsTx.commandsInvoked, false).length === 0);
}

// ── Red-team closures (each maps to a demonstrated dodge in the external report) ──
{
  const KEY = 'AKIA' + '0123456789ABCDEF';   // built by concat so this test file can't self-trip the scanner
  // D2 — a forged persisted status:"done" is NOT trusted; status is recomputed from the diff.
  ok('D2: a forged status:"done" with the deliverable absent from the diff is recomputed to pending',
    updateTaskLedger([{ id: 't1', task: 'build the parser in parser.js', deliverable: ['parser.js'], status: 'done' }], ['build the parser in parser.js'], '')[0].status === 'pending');
  ok('D2: a real delivery in the diff still marks done (recompute is correct, not just strict)',
    updateTaskLedger([], ['build the parser in parser.js'], '+++ b/parser.js\n+export const p = 1;')[0].status === 'done');
  // D3 — secret split across a string concat is caught (runtime value identical).
  ok('D3: a concat-split AWS key ("AKIA"+"…") is flagged as a hardcoded secret',
    analyze({ claim: '', diff: `+++ b/c.js\n+const k = "AKIA" + "0123456789ABCDEF";` }).some(f => f.cls === 'C1'));
  // D4 — tautological RLS predicate (1=1) is as permissive as USING(true).
  ok('D4: USING(1=1) is flagged as a permissive policy, same as USING(true)',
    analyze({ claim: '', diff: `+++ b/m.sql\n+CREATE POLICY p ON t FOR SELECT TO anon USING (1=1);` }).some(f => f.cls === 'B3'));
  // D5 — lowercase stub marker is caught.
  ok('D5: a lowercase "// todo" is flagged as a stub (case-insensitive)',
    analyze({ claim: '', diff: `+++ b/x.js\n+function f(){ // todo implement\n+}` }).some(f => f.cls === 2));
  // MCP — SQL run through an MCP DB tool (no file, no git diff) is captured for the scanners.
  ok('MCP: SQL from an mcp__*execute_sql tool_use is captured into parsed.mcpSql',
    /USING\s*\(true\)/i.test(parseTranscript(JSON.stringify({ type: 'assistant', message: { content: [{ type: 'tool_use', name: 'mcp__claude_ai_Supabase__execute_sql', input: { query: 'CREATE POLICY p ON t USING (true);' } }] } })).mcpSql));
  // D8 — the session baseline is now referee state; an out-of-band rewrite/delete is tamper-flagged.
  ok('D8: a write to *.baseline.json trips the referee-tamper check',
    refereeTamper('+++ b/.claude/groundtruth/s.baseline.json\n+{}', new Set(), false).some(f => f.cls === 'tamper'));
}

// ── D9: out-of-band tamper via the SessionStart hash snapshot (catches the Bash/MCP channel the diff misses) ──
{
  const CFG = '.claude/groundtruth/config.json';
  const T = [{ rel: CFG, ratifiedBy: 'groundtruth-block' }];
  const snap = (files, extra = {}) => ({ files, sig: null, sigValid: null, targets: T, ...extra });
  ok('snapshot: unchanged referee files → no tamper',
    compareSnapshot(snap({ [CFG]: 'aaaa' }), { [CFG]: 'aaaa' }).length === 0);
  // Phase 4: in the UNSIGNED regime the hash-compare can't be authoritative (best-effort), so an out-of-band
  // change is a quiet integrity_note (awareness only), NOT a per-turn finding — the empirical noise fix.
  ok('snapshot (unsigned): a hash that changed OUT-OF-BAND → quiet integrity_note (info), not a finding',
    compareSnapshot(snap({ [CFG]: 'aaaa' }), { [CFG]: 'bbbb' }).every(f => f.cls === 'integrity_note' && f.sev === 'info'));
  ok('snapshot: the same change RATIFIED by /groundtruth-block is legitimate (not flagged at all)',
    compareSnapshot(snap({ [CFG]: 'aaaa' }), { [CFG]: 'bbbb' }, new Set(['groundtruth-block'])).length === 0);
  ok('snapshot (unsigned): a referee file that VANISHED → quiet integrity_note (info)',
    compareSnapshot(snap({ [CFG]: 'aaaa' }), {}).every(f => f.cls === 'integrity_note' && f.sev === 'info'));
  // In the TRUSTWORTHY regime (key + valid sig) the out-of-band change IS a loud finding, env-anchored.
  ok('snapshot (trustworthy): out-of-band change is a tamper finding, severity anchored to env (block when env set)',
    compareSnapshot(snap({ [CFG]: 'aaaa' }, { sig: 'x', sigValid: true, keyed: true }), { [CFG]: 'bbbb' }, new Set(), /*envBlock*/ true, /*keyConfigured*/ true)[0].sev === 'block');
  ok('snapshot: a SIGNED snapshot whose signature no longer verifies → tamper (the snapshot itself was forged)',
    compareSnapshot(snap({ [CFG]: 'aaaa' }, { sig: 'deadbeef', sigValid: false }), { [CFG]: 'aaaa' }).some(f => /signature INVALID/i.test(f.msg)));
  ok('snapshot: no snapshot (SessionStart did not run) → nothing to compare, no crash',
    compareSnapshot(null, { x: 'y' }).length === 0);
  // The verdict declares its own integrity SCOPE so a green doesn't overclaim (T1 honesty).
  ok('integrityScope: NO key → "BEST-EFFORT" + names the laundered-write gap + points to CI',
    /BEST-EFFORT/.test(integrityScope(false)) && /launder/i.test(integrityScope(false)) && /CI/.test(integrityScope(false)));
  ok('integrityScope: key set → states it holds only if the key is OUT of the agent\'s shell + CI',
    /signed/i.test(integrityScope(true)) && /shell/i.test(integrityScope(true)) && /CI/.test(integrityScope(true)));
  ok('renderCard surfaces the integrity scope line on the card',
    /Integrity:/.test(renderCard([], { session: 's', intent: 'x', integrity: integrityScope(false) })));
  // H7: a snapshot that WAS keyed (keyed:true) but is now UNSIGNED was downgraded to evade the seal → tamper,
  // block-eligible under env, even if hashes match (the naive downgrade that leaves keyed:true intact).
  ok('H7: keyed snapshot now UNSIGNED (downgraded) → tamper, even when hashes match',
    compareSnapshot(snap({ [CFG]: 'aaaa' }, { sig: null, sigValid: null, keyed: true }), { [CFG]: 'aaaa' }, new Set(), true, /*keyConfigured*/ true).some(f => f.cls === 'tamper' && f.sev === 'block' && /UNSIGNED|downgraded/i.test(f.msg)));
  ok('H7: key configured + a VALID signature + unchanged hashes → clean (no false alarm)',
    compareSnapshot(snap({ [CFG]: 'aaaa' }, { sig: 'x', sigValid: true, keyed: true }), { [CFG]: 'aaaa' }, new Set(), false, true).length === 0);
  ok('H7: NO key configured → unsigned snapshot is accepted (documented limit, hash-compare only)',
    compareSnapshot(snap({ [CFG]: 'aaaa' }, { sig: null, sigValid: null }), { [CFG]: 'aaaa' }, new Set(), false, false).length === 0);
  // VERSION-SKEW regression (the live false-BLOCK): a KEYLESS snapshot (written before GROUNDTRUTH_KEY was
  // set, or by an older plugin) read under a now-configured key must NOT block — it WARNs, never blocks.
  ok('skew: keyless snapshot (keyed:false) under a now-set key → WARN only, never a block (no false-block)',
    (() => { const fs = compareSnapshot(snap({ [CFG]: 'aaaa' }, { sig: null, sigValid: null, keyed: false }), { [CFG]: 'aaaa' }, new Set(), /*envBlock*/ true, /*keyConfigured*/ true);
      return fs.length === 1 && fs[0].sev === 'warn' && fs.every(f => f.sev !== 'block'); })());
  // Back-compat: a pre-fix snapshot with NO `keyed` field but a VALID sig is treated as keyed (clean, no warn).
  ok('skew: a pre-fix snapshot (no keyed field) with a valid sig is still treated as keyed → clean',
    compareSnapshot(snap({ [CFG]: 'aaaa' }, { sig: 'x', sigValid: true }), { [CFG]: 'aaaa' }, new Set(), false, true).length === 0);
}

// ── Second-pass red-team closures (H4 enumeration, D10 wedge, MCP→procedures) ──
{
  // H4 — match the constant-predicate CLASS (incl. WITH CHECK + non-equality), not a hand-list; scoped passes.
  ok('H4: WITH CHECK (true) — anon WRITE — is flagged (the gate covered only USING before)',
    analyze({ claim: '', diff: `+++ b/m.sql\n+CREATE POLICY p ON t FOR INSERT TO anon WITH CHECK (true);` }).some(f => f.cls === 'B3'));
  ok('H4: USING (1 < 2) (a non-equality tautology) is flagged',
    analyze({ claim: '', diff: `+++ b/m.sql\n+CREATE POLICY p ON t FOR SELECT TO anon USING (1 < 2);` }).some(f => f.cls === 'B3'));
  ok('H4: a SCOPED predicate (auth.uid() = user_id) WITHOUT TO anon/public is NOT flagged (no over-block)',
    !analyze({ claim: '', diff: `+++ b/m.sql\n+CREATE POLICY p ON t FOR SELECT USING (auth.uid() = user_id);` }).some(f => f.cls === 'B3'));
  // H8 — the predicate regex can always be wrapped (((1=1)), true OR false); gate on the GRANT instead.
  ok('H8: wrapped/compound tautology under TO anon/public is caught by the grant-gate (predicate-agnostic)',
    analyze({ claim: '', diff: `+++ b/m.sql\n+CREATE POLICY p ON t FOR ALL TO public USING ((1=1)) WITH CHECK (true OR false);` }).some(f => f.cls === 'B3'));
  ok('H8: a TO public policy WITH a scoped predicate is surfaced for confirmation (warn, not block)',
    (() => { const fs = analyze({ claim: '', diff: `+++ b/m.sql\n+CREATE POLICY p ON t FOR SELECT TO public USING (auth.uid() = user_id);` }).filter(f => f.cls === 'B3'); return fs.length === 1 && fs[0].sev === 'warn'; })());

  // D10 wedge — gaming increments toward escalation; it no longer freezes into an infinite block.
  ok('D10 wedge: a gamed retry AT the cap ESCALATES (terminates at human review, never wedges)',
    remediationDecision({ attempts: 2, gamed: true, cap: 2 }).action === 'escalate');
  ok('D10: a gamed retry BELOW the cap still holds the block (gaming is not an escape hatch)',
    remediationDecision({ attempts: 1, gamed: true, cap: 2 }).action === 'block');
  // GAMED_FILE_RE: gaming = test/spec edits only. A referee-state path (left in the CUMULATIVE diff by a
  // LEGIT earlier `/groundtruth-rules` arming) must NOT count as gaming on a later turn (the false "GAMING
  // DETECTED" bug). Tests/specs DO count.
  ok('gamed: a test-file edit is gaming', GAMED_FILE_RE.test('api/foo.test.js') && GAMED_FILE_RE.test('src/__tests__/x.js') && GAMED_FILE_RE.test('spec/a_spec.rb'));
  ok('gamed: a referee-state write is NOT gaming (refereeTamper guards the ledger; avoids false GAMING DETECTED)',
    !GAMED_FILE_RE.test('.claude/groundtruth/compiled-rules.json') && !GAMED_FILE_RE.test('.claude/groundtruth/x.tasks.json'));
  ok('gamed: a normal source edit is NOT gaming', !GAMED_FILE_RE.test('src/app.js') && !GAMED_FILE_RE.test('api/rounds.js'));

  // MCP→procedures — a migration run via MCP is in the command stream runProcedures inspects.
  const tx = parseTranscript(JSON.stringify({ type: 'assistant', message: { content: [{ type: 'tool_use', name: 'mcp__claude_ai_Supabase__apply_migration', input: { query: 'ALTER TABLE x ADD COLUMN y int;' } }] } }));
  ok('MCP→procedures: an MCP migration is captured as a command (not just SQL)',
    (tx.mcpCmds || []).some(c => /apply_migration/.test(c)));
  ok('MCP→procedures: runProcedures fires forbid_present over the MCP command stream',
    runProcedures(tx.mcpCmds || [], [{ kind: 'forbid_present', match: 'apply_migration', message: 'no prod migration via MCP' }]).length === 1);
}

// ── #2 grounding regression guard (REAL git, not injected): a doc forbids `map`, the code uses `.map(`.
//    compile() must classify it 'review' — which only happens if codeHits' `git grep -P` honours \b. A
//    regress to `git grep -E` (which silently drops \b → 0 hits → 'armable') FAILS this, not just a comment.
{
  let repo;
  try { repo = mkdtempSync(pathJoin(tmpdir(), 'gt-ground-')); }
  catch { repo = mkdtempSync(pathJoin(process.cwd(), '.gt-ground-')); }   // fall back to cwd if tmp isn't writable
  try {
    const git = (args) => execFileSync('git', args, { cwd: repo, stdio: ['ignore', 'pipe', 'ignore'] });
    git(['init', '-q']); git(['config', 'user.email', 't@t']); git(['config', 'user.name', 't']);
    fsWrite(pathJoin(repo, 'CLAUDE.md'), 'Image rules: show the event itself, never `map` as a round image.\n');
    fsWrite(pathJoin(repo, 'a.js'), 'const out = items.map(x => x + 1);\n');
    git(['add', '-A']);
    const mapRule = compile(repo).find(c => /\\bmap\\b/.test(c.line_re));
    ok('grounding (REAL git grep -P): a forbidden token present in code grounds as "review", not "armable"',
      !!mapRule && mapRule.status === 'review' && mapRule.hits >= 1);
  } finally { try { rmSync(repo, { recursive: true, force: true }); } catch {} }
}

// ── compile() validation gates: a seed rule must (1) compile at runtime and (2) match its positive_example
//    before it can be 'armable' — else it routes to 'review' with a reason. Closes the "armed but never
//    fires" hole (LLM/hand-authored regex that compiles under PCRE grounding but is inert or wrong in JS). ──
{
  let repo;
  try { repo = mkdtempSync(pathJoin(tmpdir(), 'gt-validate-')); }
  catch { repo = mkdtempSync(pathJoin(process.cwd(), '.gt-validate-')); }
  try {
    const git = (args) => execFileSync('git', args, { cwd: repo, stdio: ['ignore', 'pipe', 'ignore'] });
    git(['init', '-q']); git(['config', 'user.email', 't@t']); git(['config', 'user.name', 't']);
    fsMkdir(pathJoin(repo, '.claude', 'groundtruth'), { recursive: true });
    fsWrite(pathJoin(repo, '.claude', 'groundtruth', 'seed-rules.json'), JSON.stringify([
      { id: 'seed-ci', kind: 'forbid_in_added', file_re: '\\.sql$', line_re: '(?i)\\bCREATE\\s+TABLE\\b', message: 'x', positive_example: 'CREATE TABLE t (id int)' },
      { id: 'seed-broken', kind: 'forbid_in_added', file_re: '\\.js$', line_re: '(', message: 'x', positive_example: 'y' },
      { id: 'seed-nomatch', kind: 'forbid_in_added', file_re: '\\.js$', line_re: '\\bfoo\\b', message: 'x', positive_example: 'bar' },
    ]));
    const P = compile(repo);
    const g = (id) => P.find(c => c.id === id);
    ok('compile: a `(?i)` seed rule is normalized and grounds "armable" (PCRE-only pattern no longer dies)',
      g('seed-ci') && g('seed-ci').status === 'armable');
    ok('compile: a seed rule whose regex will not compile → "review" with a reason (never auto-armable)',
      g('seed-broken') && g('seed-broken').status === 'review' && /does not compile/i.test(g('seed-broken').reason || ''));
    ok('compile: a seed rule whose line_re does not match its positive_example → "review" (proven-not-to-fire)',
      g('seed-nomatch') && g('seed-nomatch').status === 'review' && /positive_example/i.test(g('seed-nomatch').reason || ''));
  } finally { try { rmSync(repo, { recursive: true, force: true }); } catch {} }
}

// ── Task ledger: persistent, GROUNDED — "done" only when the deliverable lands, never on acknowledgment ──
{
  const asks = ['Build the engine in engine.mjs', 'just thinking out loud here'];
  let ledger = updateTaskLedger([], asks, '');
  ok('ledger: tracks an ask naming a deliverable as pending', ledger.length === 1 && ledger[0].status === 'pending');
  ok('ledger: ignores an ask that names no deliverable (abstain)', !ledger.some(t => /thinking/.test(t.task)));
  ledger = updateTaskLedger(ledger, asks, '+++ b/engine.mjs\n+export const x = 1;');
  ok('ledger: marks DONE only once the deliverable grounds in the diff', ledger[0].status === 'done');
  ok('ledger: an acknowledgment with NO delivery does NOT close a pending task',
    updateTaskLedger([{ task: 'Build the engine in engine.mjs', deliverable: ['engine.mjs'], status: 'pending' }], asks, '')[0].status === 'pending');
  ok('ledger: a human-set "deferred" is preserved, never reopened',
    updateTaskLedger([{ task: 'Build the engine in engine.mjs', deliverable: ['engine.mjs'], status: 'deferred' }], asks, '')[0].status === 'deferred');
}

// ── False-positive guard + anti-gaming (grounded in a real gaming case: an agent self-marked
//    a READ of CLAUDE.md, a /tmp scratchpad temp, and the hook's own message as 'deferred' to dodge) ──
{
  ok('ledger: a READ of a convention doc is NOT a deliverable ("read CLAUDE.md …" → no phantom task)',
    updateTaskLedger([], ['read CLAUDE.md and the skills, then continue'], '').length === 0);
  ok('ledger: but WRITING a convention doc IS tracked ("update CLAUDE.md with the rule")',
    updateTaskLedger([], ['update CLAUDE.md with the new rule'], '').some(t => t.deliverable.includes('CLAUDE.md')));
  ok('ledger: a non-"update" write verb still counts — "fix CLAUDE.md" is tracked (no free skip)',
    updateTaskLedger([], ['fix the broken rule in CLAUDE.md'], '').some(t => t.deliverable.includes('CLAUDE.md')));
  ok('ledger: an out-of-repo scratchpad temp is NOT a deliverable (/private/tmp/…/cand_3836.json)',
    updateTaskLedger([], ['fix the image in /private/tmp/scratch/cand_3836.json'], '').length === 0);
  ok('ledger: the tool\'s OWN tasks.json is NOT a deliverable (no circular self-reference)',
    updateTaskLedger([], ['record the result in tasks.json'], '').length === 0);
  ok('ledger: a real source file is still tracked, and closes when it lands in the diff',
    updateTaskLedger([], ['fix the parser in utils.js'], '').length === 1 &&
    updateTaskLedger([], ['fix the parser in utils.js'], '+++ b/utils.js\n+code')[0].status === 'done');
  ok('openLoops: same filtering — a read of CLAUDE.md is not an open loop',
    openLoops(['read CLAUDE.md before you start'], '').length === 0);

  // Regression: a human writes `schema.md` for the file the repo calls `SCHEMA.md`. Filename matching
  // MUST be case-insensitive, or the delivered work reads as a false open-loop / silent no-op (real bug).
  ok('openLoops: `schema.md` in the ask grounds against `SCHEMA.md` in the diff (case-insensitive filename)',
    openLoops(['write these entries to schema.md'], '+++ b/hindsight-vercel/SCHEMA.md\n+- new col').length === 0);
  ok('ledger: `schema.md` ask closes when `SCHEMA.md` lands in the diff (case-insensitive)',
    updateTaskLedger([], ['write these entries to schema.md'], '+++ b/hindsight-vercel/SCHEMA.md\n+- x')[0].status === 'done');
  ok('Class 3: a claim about `schema.md` is NOT a no-op when `SCHEMA.md` is in the diff',
    !analyze({ claim: 'updated schema.md with the new table', diff: '+++ b/hindsight-vercel/SCHEMA.md\n+- x' }).some(f => f.cls === 3));
  // Precision guard: case-insensitivity is for FILENAMES only — a camelCase symbol stays case-sensitive.
  ok('openLoops: a camelCase symbol stays case-sensitive (fooBar ≠ foobar)',
    openLoops(['wire up fooBar'], '+++ b/a.js\n+const foobar = 1').length === 1);

  // parseTranscript: harness injections delivered as user turns are NOT asks.
  const inj = [
    JSON.stringify({ type: 'user', message: { content: [{ type: 'text', text: '<task-notification><task-id>w7r</task-id> done</task-notification>' }] } }),
    JSON.stringify({ type: 'user', message: { content: [{ type: 'text', text: 'Stop hook feedback: Groundtruth blocked this stop (attempt 1).' }] } }),
    JSON.stringify({ type: 'user', message: { content: [{ type: 'text', text: 'Continue the refactor, fix the bug in cart.js' }] } }),
  ].join('\n');
  const pa = parseTranscript(inj).asks;
  ok('parseTranscript: a <task-notification> turn is NOT captured as a user ask', !pa.some(a => /task-notification|w7r/.test(a)));
  ok('parseTranscript: Stop-hook feedback echoed as a turn is NOT a user ask (kills the circular loop)',
    !pa.some(a => /hook feedback|blocked this stop/i.test(a)));
  ok('parseTranscript: the REAL ask in the same transcript still survives', pa.some(a => /Continue the refactor/.test(a)));

  // #1 — POSITIVE structural signal (not a text blocklist): the harness's own injection markers exclude
  // a turn even when its text looks like a real ask, so a NEW injection type is caught too.
  const structural = [
    JSON.stringify({ type: 'user', isMeta: true, message: { content: [{ type: 'text', text: 'Please refactor everything in app.js now' }] } }),
    JSON.stringify({ type: 'user', toolUseResult: { ok: 1 }, message: { content: [{ type: 'text', text: 'build the dashboard in dash.js' }] } }),
    JSON.stringify({ type: 'user', promptSource: 'sdk', message: { content: [{ type: 'text', text: 'add a cache to fetch.js' }] } }),
  ].join('\n');
  const sa = parseTranscript(structural).asks;
  ok('parseTranscript: isMeta / toolUseResult turns are excluded structurally even when the text reads like an ask',
    !sa.some(a => /app\.js|dash\.js/.test(a)) && sa.some(a => /fetch\.js/.test(a)));

  // #3 — confirmation is UNFORGEABLE: only the user typing `defer <id>` in a real turn honors a deferral.
  // An agent-written 'deferred' (in tasks.json OR any file it could forge) is re-opened to pending.
  const led = [{ id: taskId('continue the refactor'), task: 'continue the refactor', deliverable: ['x.js'], status: 'deferred' },
               { id: taskId('also fix login'), task: 'also fix login', deliverable: ['login.js'], status: 'deferred' }];
  const confirmed = humanDeferrals([`yeah defer ${taskId('also fix login')} for now, skip it`]);   // the user typed it
  ok('humanDeferrals: extracts the id from a user-typed "defer <id>"', confirmed.has(taskId('also fix login')));
  const after = applyConfirmedDeferrals(led, confirmed);
  ok('deferral: an agent-written deferral the USER did not confirm is re-opened to pending (the dodge fails)',
    after.find(t => t.task === 'continue the refactor').status === 'pending' &&
    after.find(t => t.task === 'continue the refactor').deferRequested === true);
  ok('deferral: a deferral the USER typed `defer <id>` for is honored (stays deferred)',
    after.find(t => t.task === 'also fix login').status === 'deferred');
  ok('deferral: forging a confirmations FILE/Set the user never typed does nothing (empty human set → all re-opened)',
    applyConfirmedDeferrals(led, humanDeferrals([])).every(t => t.status === 'pending'));
  ok('taskId: stable + deterministic over the task text', taskId('continue the refactor') === taskId('continue the refactor') && /^t[0-9a-z]{1,4}$/.test(taskId('x')));

  // a deferred (human-confirmed) task is still surfaced for transparency (never silent)
  const card = renderCard([{ cls: 'deferred', sev: 'warn', msg: 'deferred (human-confirmed) — "also fix login"' }],
    { session: 'sess', intent: 'work' });
  ok('renderCard: a human-confirmed deferral is surfaced (transparent, not silent)',
    /human-confirmed/i.test(card) && /also fix login/.test(card));
}

ok('loadGtConfig: a missing config file → {} (safe default, never crashes, block stays off)',
  JSON.stringify(loadGtConfig('/nonexistent/path/xyz')) === '{}');

// proposedStale — manual-edit recompile gate (option 1): recompile PROPOSED when a rule doc is newer.
ok('proposedStale: no proposed file yet → due (recompile)', proposedStale(null, [100, 200]) === true);
ok('proposedStale: a rule doc newer than proposed → due', proposedStale(100, [50, 150]) === true);
ok('proposedStale: all docs older than proposed → NOT due', proposedStale(200, [100, 150]) === false);
ok('proposedStale: no rule docs at all → NOT due', proposedStale(200, []) === false);
ok('proposedStale: an unreadable doc (null mtime) is ignored, not treated as newer', proposedStale(200, [null, 100]) === false);

// ── request/non-request gate — the "conversational aside → open loop" FP fix (deterministic, no LLM) ──
ok('isTrackableRequest: an observation ("I can see a 304, it\'s fine") is NOT a request',
  isTrackableRequest("I can see a 304 in `handleUpload`, it's fine") === false);
ok('isTrackableRequest: dismissal with a NEGATED verb ("no fix needed") is NOT a request (the "no fix" trap)',
  isTrackableRequest("the 304 in `handleUpload` is fine, no fix needed") === false);
ok('isTrackableRequest: a compound aside that ALSO commands a real fix IS a request (verb survives strip)',
  isTrackableRequest("the 304 is fine but fix the 500 in retry.js") === true);
ok('isTrackableRequest: a plain interrogative naming a file ("is report.js right?") is NOT a request',
  isTrackableRequest('is report.js right?') === false);
ok('isTrackableRequest: a plain imperative IS a request',
  isTrackableRequest('add retry with backoff to src/upload.js') === true);
ok('isTrackableRequest: "ignore the cache.js warning for now" is NOT a request',
  isTrackableRequest('ignore the cache.js warning for now') === false);

// end-to-end: an observation is a nag-free SOFT aside (demote-don't-drop), a real request is a HARD task.
ok('openLoops (HARD only): an observation naming a backtick token mints NO open loop',
  openLoops(["I can see a 304 in `handleUpload`, it's fine, no fix needed"], '').length === 0);
ok('openLoops (HARD only): a real ask naming an absent deliverable STILL opens a loop',
  openLoops(['add a csv export to report.js'], '').length === 1);
ok('ledger tier: an observation naming a token creates a SOFT task (demote-don\'t-drop, never blocks)',
  (() => { const t = updateTaskLedger([], ["the 304 in `handleUpload` is fine, no fix needed"], ''); return t.length === 1 && t[0].tier === 'soft'; })());
ok('ledger tier: a real imperative request creates a HARD task',
  (() => { const t = updateTaskLedger([], ['fix the retry in retry.js'], ''); return t.length === 1 && t[0].tier === 'hard'; })());

// ── Phase 1: example-secret allowlist + synthetic-marker demotion (kills the block-severity FP) ──
ok('isSecret: the AWS docs example key is recognized but BENIGN (allowlisted → demote)',
  isSecret('const k = "AKIAIOSFODNN7EXAMPLE";').benign === true);
ok('isSecret: a real-shaped AWS key (no marker) is NOT benign → still blocks',
  isSecret('const k = "AKIA4KNZ7QW2RJ9DP3VH";').benign === false);
// C1 regression: a REAL-format key is NOT demoted by attacker-choosable line context (a `FAKE_` var name,
// a `// example` comment). Only the KEY TOKEN itself (allowlisted or marker-inside) demotes.
ok('isSecret: a real-shaped key on a FAKE_-marked var name STILL blocks (line context is attacker-choosable)',
  isSecret('const FAKE_KEY = "AKIA4KNZ7QW2RJ9DP3VH";').benign === false);
ok('isSecret: a real-shaped key with an "// example" comment STILL blocks (C1 bypass closed)',
  isSecret('const awsKey = "AKIA4KNZ7QW2RJ9DP3VH"; // see example in docs').benign === false);
ok('isSecret: a key whose OWN token self-marks (…EXAMPLE) is benign',
  isSecret('const k = "AKIAIOSFODNN7EXAMPLE";').benign === true);
ok('analyze: an example key added → WARN, not block (no false halt)',
  analyze({ claim: '', diff: '+++ b/config.js\n+const k = "AKIAIOSFODNN7EXAMPLE";' }).some(f => f.cls === 'C1' && f.sev === 'warn'));
ok('analyze: a real-shaped key added → BLOCK (real leak still halts)',
  analyze({ claim: '', diff: '+++ b/config.js\n+const k = "AKIA4KNZ7QW2RJ9DP3VH";' }).some(f => f.cls === 'C1' && f.sev === 'block'));

// ── Phase 2: position-aware stub markers (comment/prose only — string/regex/JSON/fence = mention) ──
ok('C2 self-match FIX: a TODO inside a regex literal is NOT a stub',
  !has(analyze({ claim: '', diff: '+++ b/x.js\n+const RE = /\\b(TODO|FIXME|XXX|HACK)\\b/i;' }), 2));
ok('C2 FIX: a TODO inside a string literal is NOT a stub',
  !has(analyze({ claim: '', diff: '+++ b/x.js\n+const msg = "handle TODO items later";' }), 2));
ok('C2 FIX: a TODO inside a JSON string value is NOT a stub',
  !has(analyze({ claim: '', diff: '+++ b/data.json\n+  "note": "flagged a TODO by mistake"' }), 2));
ok('C2 still fires: a real // TODO comment',
  has(analyze({ claim: '', diff: '+++ b/x.js\n+  // TODO: wire up backoff' }), 2));
ok('C2 still fires: a TODO inside a /* block comment */',
  has(analyze({ claim: '', diff: '+++ b/x.js\n+  /* TODO: fix */' }), 2));
ok('C2 FIX (md): a // TODO inside a fenced code block is NOT a stub (quotation)',
  !has(analyze({ claim: '', diff: '+++ b/README.md\n+```\n+  // TODO: demo card\n+```' }), 2));
ok('C2 (md): a TODO in markdown PROSE still counts',
  has(analyze({ claim: '', diff: '+++ b/README.md\n+TODO: document the API' }), 2));
ok('audit scanContent: TODO in a regex literal is silent (position-aware)',
  !scanContent('x.js', 'const RE = /\\b(TODO)\\b/;\n').some(f => f.cls === 2));
ok('audit scanContent: a real // TODO comment still fires',
  scanContent('x.js', '// TODO: real\n').some(f => f.cls === 2));
ok('C2 FIX: an enumeration of markers in a comment (TODO/FIXME) is documentation, not a stub',
  !has(analyze({ claim: '', diff: '+++ b/x.js\n+// forbidden markers: (TODO/FIXME)' }), 2));
ok('C2 still fires: a real marker with a colon in a doc-comment continuation',
  scanContent('x.js', '/* handler\n * TODO: implement retry\n */\n').some(f => f.cls === 2));

// ── Phase 2b: member-access-safe boundary for CALL-forbidding rules (the $eval FP) ──
ok('call-rule: `\\beval\\s*\\(` does NOT match a method call page.$eval(',
  !compileRuleRe('\\beval\\s*\\(').test("await page.$eval('#x')"));
ok('call-rule: `\\beval\\s*\\(` does NOT match x.eval(',
  !compileRuleRe('\\beval\\s*\\(').test('obj.eval(src)'));
ok('call-rule: `\\beval\\s*\\(` STILL matches the global eval(',
  compileRuleRe('\\beval\\s*\\(').test('const r = eval(userExpr);'));
ok('identifier-rule `\\bsignup_date\\b` UNTOUCHED — still matches member access row.signup_date',
  compileRuleRe('\\bsignup_date\\b').test('const d = row.signup_date;'));
const _evalRule = [{ id: 'no-eval', kind: 'forbid_in_added', file_re: '\\.(js|mjs)$', line_re: '\\beval\\s*\\(', message: 'never use eval()' }];
ok('runCompiledRules: page.$eval in added code is NOT flagged (Playwright API, not global eval)',
  !runCompiledRules('+++ b/ui-smoke.mjs\n+  const t = await page.$eval("#x", e => e.textContent);', _evalRule).length);
ok('runCompiledRules: a real eval( in added code IS flagged',
  runCompiledRules('+++ b/a.js\n+  const r = eval(userInput);', _evalRule).some(f => f.cls === 'R'));

// ── Phase 3: self-state / scratchpad exclusion, rule provenance, rule comment-position ──
ok('excludedScanPath: absolute / parent-escape / scratchpad / self-state are excluded',
  excludedScanPath('/Users/x/repo/a.js') && excludedScanPath('../up.js') &&
  excludedScanPath('foo/scratchpad/b.js') && excludedScanPath('.claude/groundtruth/x.json'));
ok('excludedScanPath: a normal repo path is NOT excluded', !excludedScanPath('src/app.js') && !excludedScanPath('hooks/groundtruth.mjs'));
ok('dropExcludedFiles: an excluded file block is stripped, a normal one kept', (() => {
  const d = '+++ b/.claude/groundtruth/tasks.json\n+{"x":1}\n+++ b/src/app.js\n+const y = 2;';
  const r = dropExcludedFiles(d);
  return !r.includes('tasks.json') && r.includes('src/app.js');
})());
{
  const evalRule = [{ id: 'no-eval', kind: 'forbid_in_added', file_re: '\\.js$', line_re: '\\beval\\s*\\(', message: 'never use eval()' }];
  ok('rule comment-skip: a call-rule does NOT fire on eval() mentioned in a // comment',
    !runCompiledRules('+++ b/x.js\n+  // never call eval() here', evalRule).length);
  ok('rule comment-skip: the same call-rule DOES fire on a real eval() in code',
    runCompiledRules('+++ b/x.js\n+  const r = eval(src);', evalRule).some(f => f.cls === 'R'));
  const provRule = [{ id: 'no-foo', source: 'extracted from ARCHITECTURE.md:5', kind: 'forbid_in_added', file_re: '\\.md$', line_re: '\\bfoobar\\b', message: 'avoid foobar' }];
  ok('rule provenance: a rule extracted from ARCHITECTURE.md does NOT fire on ARCHITECTURE.md itself',
    !runCompiledRules('+++ b/ARCHITECTURE.md\n+never write foobar in code', provRule).length);
  ok('rule provenance: the same rule STILL fires on a different file',
    runCompiledRules('+++ b/other.md\n+here is foobar', provRule).some(f => f.cls === 'R'));
}
// ── Phase 5c: phantom-import parse (an import-shaped substring inside a string is not a real import) ──
ok('phantom parse: an import inside a string literal (test fixture) is NOT flagged',
  !has(analyze({ claim: '', diff: '+++ b/x.js\n+const d = \'+import y from "./nope-xyz"\';' }), 4));
ok('phantom parse: a real unresolved import IS still flagged',
  has(analyze({ claim: '', diff: '+++ b/x.js\n+import y from "./nope-xyz-123";' }), 4));

// ── Phase 4: tamper re-plumb — unsigned out-of-band = quiet note, not a per-turn finding ──
{
  const snap = { files: { x: 'hashA' }, targets: [{ rel: 'x', ratifiedBy: null }], sig: null, sigValid: null, keyed: false };
  const unsigned = compareSnapshot(snap, { x: 'hashB' }, new Set(), false, false);
  ok('tamper (unsigned regime): an out-of-band change is a quiet integrity_note, NOT a tamper finding',
    unsigned.length === 1 && unsigned[0].cls === 'integrity_note' && unsigned[0].sev === 'info');
  const signed = { files: { x: 'hashA' }, targets: [{ rel: 'x', ratifiedBy: null }], sig: 'sig', sigValid: true, keyed: true };
  const trusted = compareSnapshot(signed, { x: 'hashB' }, new Set(), false, true);
  ok('tamper (trustworthy regime, key + valid sig): an out-of-band change IS a loud tamper finding',
    trusted.some(f => f.cls === 'tamper' && (f.sev === 'warn' || f.sev === 'block')));
  const card = renderCard([{ cls: 'integrity_note', sev: 'info', msg: 'compiled-rules.json differs' }], { intent: 'add a button to report.js' });
  ok('renderCard: an integrity_note does NOT flip the verdict (stays Told & Done 🟢)',
    card.includes('Told & Done') && !card.includes("rewrote Groundtruth's OWN state"));
  ok('renderCard: the integrity_note still shows as an awareness footer',
    card.includes('Integrity note (awareness only'));
}

// ── Phase 6: open-loop suite — tiers, clause-binding, novelty/paste-provenance, comment-vector, nag-once ──
{
  const c = classifyDeliverables('the 304 in `handleUpload` is fine, but fix retry.js');
  ok('clause-binding: "…handleUpload is fine, but fix retry.js" → retry.js HARD, handleUpload SOFT (not both)',
    c.hard.includes('retry.js') && c.soft.includes('handleUpload') && !c.hard.includes('handleUpload'));
}
// C2 regression: token-novelty via AGENT text was REMOVED (agent-influenceable). The agent naming the
// deliverable in its OWN reply must NOT demote its own ask — classifyDeliverables ignores agent text entirely.
ok('C2: an agent naming the deliverable in its reply canNOT demote the ask (no agent-text novelty)',
  classifyDeliverables('add a csv export to report.js').hard.includes('report.js'));
ok('a user-novel token in a real request is HARD',
  classifyDeliverables('add a guard to app.js').hard.includes('app.js'));
// M2 regression: paste-provenance computed on the FULL ask (fence survives clause-splitting).
ok('paste-provenance (fence): a token only inside a ``` fence is a reference (SOFT), not a HARD open loop',
  (() => { const c = classifyDeliverables('why does this crash?\n```\nconst x = doTheThing(payload)\n```'); return c.soft.includes('doTheThing') && !c.hard.includes('doTheThing'); })());
ok('paste-provenance (stack-trace): a filename only in a `file.js:line` ref is SOFT, a requested symbol stays HARD',
  (() => { const c = classifyDeliverables('the error at stackFrame.js:42 — add a guardClause'); return c.soft.includes('stackFrame.js') && c.hard.includes('guardClause'); })());
// M1 regression: polite/omitted imperatives are real requests (HARD), not demoted questions.
ok('M1: "could you move gameState into state.js?" is a HARD request (not a demoted question)',
  classifyDeliverables('could you move gameState into state.js?').hard.includes('state.js'));
ok('M1: "can you drop the retry logic from queue.js?" is a HARD request',
  classifyDeliverables('can you drop the retry logic from queue.js?').hard.includes('queue.js'));
// comment-vector close-fix
ok('comment-vector: a symbol delivered only in a COMMENT does NOT close the task (still pending)',
  updateTaskLedger([], ['wire up fooBar'], '+++ b/a.js\n+  // fooBar goes here')[0].status === 'pending');
ok('comment-vector: the same symbol in CODE closes the task (done)',
  updateTaskLedger([], ['wire up fooBar'], '+++ b/a.js\n+  const fooBar = 1;')[0].status === 'done');
// H1 regression: a soft token grounding must NOT close a HARD task whose real deliverable is absent.
ok('H1: a hard task is NOT closed by a soft/reference token grounding (only its own hard token closes it)',
  updateTaskLedger([], ['`handleUpload` is fine, but fix retry.js'], '+++ b/a.js\n+function handleUpload(){}')[0].status === 'pending');
{
  const t0 = { id: 't1', task: 'add retry to upload.js', deliverable: ['upload.js'], tier: 'hard', status: 'pending' };
  const s1 = surfaceOpenLoop(t0, 'working on it');
  ok('nag-once: first surface of a hard pending task → warn finding (not quiet) + marks surfaced',
    s1.finding && s1.finding.sev === 'warn' && !s1.finding.quiet && s1.task.surfaced === true);
  // H2 regression: a still-pending hard task STAYS on the card (finding emitted) but is marked quiet (not re-injected).
  const s2 = surfaceOpenLoop(s1.task, 'still going');
  ok('H2: second turn, no claim → still emits a pending finding (quiet != green) but marked quiet (not re-injected)',
    s2.finding && s2.finding.sev === 'warn' && s2.finding.quiet === true);
  ok('per-token done-match: a claim naming THIS task\'s token → BLOCK (escalate)',
    surfaceOpenLoop(s1.task, 'Done — added upload.js retry').finding?.sev === 'block');
  const other = { id: 't2', task: 'fix parser.js', deliverable: ['parser.js'], tier: 'hard', status: 'pending', surfaced: true };
  ok('per-token done-match: a generic "all done" NOT naming this token does NOT escalate it (stays warn/quiet)',
    surfaceOpenLoop(other, 'all done, everything works!').finding?.sev === 'warn');
  // M3 regression: an HONEST "still pending" disclosure naming the token must NOT false-block.
  ok('M3: "Done with parser; upload.js still pending — will do next" does NOT falsely escalate upload.js to block',
    surfaceOpenLoop(t0, 'Done with the parser; upload.js still pending — will do next').finding?.sev !== 'block');
  // Pass-2 defect B (dodge): a genuine false "done" claiming the token complete must BLOCK even if guard words
  // about OTHER work sit farther off in the sentence (proximity guard, not whole-clause).
  ok('proximity-B: "Done — upload.js is complete, nothing pending, will close out" STILL blocks (no far-away dodge)',
    surfaceOpenLoop(t0, 'Done — upload.js is complete, nothing pending, will close out').finding?.sev === 'block');
  // Pass-2 defect A (false-block): "not yet done" adjacent to the token is an honest disclosure → NOT block.
  ok('proximity-A: "upload.js not yet done" is an honest disclosure → NOT a false block',
    surfaceOpenLoop(t0, 'upload.js not yet done').finding?.sev !== 'block');
  ok('proximity-A: "parser done; upload.js not yet done" → NOT a false block on upload.js',
    surfaceOpenLoop(t0, 'parser done; upload.js not yet done').finding?.sev !== 'block');
}
ok('soft expiry: an aged-out soft aside stops nagging (no finding, marked stale)',
  (() => { const s = surfaceOpenLoop({ id: 't3', task: 'x', deliverable: ['handleFoo'], tier: 'soft', status: 'pending', surfaced: true, age: 5 }, ''); return s.finding === null && s.task.status === 'stale'; })());
ok('soft first-surface: a soft aside surfaces ONCE as info (never block, even with a done-claim)',
  (() => { const s = surfaceOpenLoop({ id: 't4', task: 'the 304 is fine', deliverable: ['handleBar'], tier: 'soft', status: 'pending' }, 'Done — handleBar shipped'); return s.finding && s.finding.sev === 'info'; })());

console.log(`\n${pass} checks passed.`);
